org: khaosdoctor
app: alura-serverless
service: api
frameworkVersion: '3'

params:
  default:
    dbName: alura-serverless
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: SJxV9oNKRtEks8un3W3jUZSkHwrxBOdZ
  prod:

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    SALT: ${param:salt}

functions:
  sendResponse:
    handler: api/handlers.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          # Validação de schema para o body da requisição
          # request:
            # schemas:
              # application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/handlers.getResult
    events:
      - httpApi:
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
